# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_Name', models.CharField(max_length=200)),
                ('Server_IP', models.CharField(max_length=15)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
                ('state', models.CharField(max_length=2)),
            ],
        ),
    ]
