# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverinfo',
            options={'verbose_name': '服务器', 'verbose_name_plural': '服务器'},
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='Server_IP',
            field=models.CharField(max_length=15, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='Server_Name',
            field=models.CharField(max_length=200, verbose_name='机器名'),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='create_date',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='state',
            field=models.CharField(max_length=2, verbose_name='状态'),
        ),
    ]
